### ISSUE TITLE
scale_factor equals 0

### ISSUE THREAD

**Issue by garci1294** [fl-yu/CUT-RUNTools-2.0#11]
Hi @fl-yu,

Quick question;

I keep on getting the wrong spikein_normalized files for my samples. I believe the issue is generating from the --scaleFactor from $path_deeptools/bamCoverage in `bulk-pipeline.sh`.

```
scale=$spikein_scale
scale_factor=`printf "%.0f" $(echo "$scale / $spikein_reads"|bc)`
```

My $scale is 10000 (the default) and $spikein_reads is 14638036. When the pipeline inserts these into the scale_factor equation, it just equals zero, and it uses 0 for normalization. My bw normalized file ends up being very small, and it doesn't look correct.

Is this what is suppose to do?

Thank you so much,
Jesus

**Comment by fl-yu** [comment]
Hi Jesus,

I am a bit surprised that 14638036 spike-in reads from your data, it is a large number. What is your library size reads?
If you believe the number is right, you may want to revise the `spikein_scale` parameter in the bulk configuration file to process your data properly.

**Comment by garci1294** [comment]
Hi @fl-yu,

I found the issue.

My total reads are 11089421.
My overall spike in alignment rate is 1.32%.

The following code is multiplying 1.32 by 11089421, which equals 14638036 `spikein_reads`.  
```
total_reads=`cat $logdir/"$base".spikein.bowtie2 | grep "reads; of these:" | awk '{print $1}' - FS=' '`
align_ratio=`cat $logdir/"$base".spikein.bowtie2 | grep "overall alignment" | awk '{print $1}' - FS=' ' | cut -f1 -d"%"`
spikein_reads=`printf "%.0f" $(echo "$total_reads * $align_ratio"|bc)`
```
Should it instead be multiplying 0.0132 by 11089421 which is 146,380 `spikein_reads`? If that is the case an easy fix would be changing the script to:

```
total_reads=`cat 210301_I23_V300101150_L4_Chord10a-H3K4me3.spikein.bowtie2 | grep "reads; of these:" | awk '{print $1}' - FS=' '`
align_percent=`cat 210301_I23_V300101150_L4_Chord10a-H3K4me3.spikein.bowtie2 | grep "overall alignment" | awk '{print $1}' - FS=' ' | cut -f1 -d"%"`
align_ratio=$(echo "$align_percent/100" | bc -l)
spikein_reads=`printf "%.0f" $(echo "$total_reads * $align_ratio"|bc)`
```

Please let me know what you think.

Thank you,
Jesus

**Comment by ldunn10** [comment]
Hi both

I was also having this issue. I agree with Jesus that there is an error with the spikein_reads calculation and so it is off by a factor of 100. I just edited the script like this (adding in the /100) and it corrected the error

spikein_reads=`printf "%.0f" $(echo "$total_reads * $align_ratio/100"|bc)`

**Comment by fl-yu** [comment]
You are right! Thank you so much, both garci1294 and ldunn10!
