### ISSUE TITLE
fimo output

### ISSUE THREAD

**Issue by KQ2012** [fl-yu/CUT-RUNTools-2.0#12]
Hi fl-yu,
I have a question with respect to the output in the peak analysis folder. What is the input for generating the heatmap such as Fig. 2e in the original CUT-RUNTools paper?  and the src/bulk/haystack_motifs.sh is the script to create it?

Thanks

**Comment by fl-yu** [comment]
Hi I do not how to produce that figure, could you contact the first and corresponding authors of original tool paper? Thanks!

**Comment by zqzneptune** [comment]
@KQ2012 Hi, you can refer to FIMO manual for more info, it is part of MEME suite. 
https://meme-suite.org/meme/tools/fimo

-Johnson
