### ISSUE TITLE
Spike-in normalization also uses CPM normalization?

### ISSUE THREAD

**Issue by isosceleswheel** [fl-yu/CUT-RUNTools-2.0#13]
Hi FLYu,

I am wondering why you use CPM normalization along with spike-in normalization in the following call to `bamCoverage`:

```
$path_deeptools/bamCoverage --bam $bam_file -o $outdir/"$base_file".spikein_normalized.bw \
                --binSize 10 \
                --normalizeUsing CPM \
                --effectiveGenomeSize $eGenomeSize \
                --scaleFactor $scale_factor
```
Why do you need to normalize by CPM if you are already normalizing by spike-in control? Don't these two normalization steps conflict?

Thanks for your insight,
David

**Comment by fl-yu** [comment]
Hi David Sorry for the delayed reply.
I don't think these two normalization steps conflict as the spike-in normalization does not handle library size at all. You may simply understand we generally use the CPM normalization and further scale the data with the factor relevant to spike-in reads.  Does this make sense to you? Please let me know how does it look for your data after the normalization.
