### ISSUE TITLE
MEME analysis issue

### ISSUE THREAD

**Issue by hchintalapudi** [fl-yu/CUT-RUNTools-2.0#15]
Hi,
I'm having issues with the MEME analysis for de novo motif finding.
Could you help me with what the issue is?

Thanks for the amazing tool!
[slurm-97220.out.txt](https://github.com/fl-yu/CUT-RUNTools-2.0/files/6791762/slurm-97220.out.txt)

_Originally posted by @hchintalapudi in https://github.com/fl-yu/CUT-RUNTools-2.0/issues/14#issuecomment-877201439_

**Comment by fl-yu** [comment]
Hi Thanks for your interest of our tool!
It seems that meme did not work properly in your case, the following is message of error first begins.
```
Log::Log4perl configuration looks suspicious: No loggers defined at /dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/meme/lib/site_perl/5.26.2/Log/Log4perl/Config.pm line 325.
Starting getsize: getsize random1000/MEME_SL_04_S4_shuf/SL_04_S4_summits_padded.fa 1> $metrics
/dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/meme/libexec/meme-5.0.2/getsize: error while loading shared libraries: libicui18n.so.58: cannot open shared object file: No such file or directory
getsize exited with error code 127
getsize failed me... at /dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/meme/bin/meme-chip line 748.
```
Sometimes there will be confilcts between meme and other software, do you install meme using conda by our tutorial?

**Comment by hchintalapudi** [comment]
I followed the conda isntallation of all dependencies and when I got this error I checked the installed pacakges in my conda env using "conda list" and did not find "meme".
So I checked this issue https://github.com/fl-yu/CUT-RUNTools-2.0/issues/2 and installed meme using conda install.

**Comment by fl-yu** [comment]
Yes that is the point! So I recommend you to create another environment for meme installation as shown in the tutorial. Hope this helps.
![image](https://user-images.githubusercontent.com/57479051/125341401-8fbebc80-e321-11eb-810f-d4b8fdf8edfe.png)

**Comment by hchintalapudi** [comment]
I actually followed these steps using environment1.yml and environment2.yml in the install dir
I have two separate envs like you mentioned above.
Yet I get these errors.
[slurm-105153.out.txt](https://github.com/fl-yu/CUT-RUNTools-2.0/files/6803838/slurm-105153.out.txt)

That's when I decided to conda install meme again in the cutruntools2 env (that was ignorant I guess)

**Comment by fl-yu** [comment]
Can you tell me why the message begins with 
```
Could not find conda environment: cutruntools2
You can list all discoverable environments with `conda info --envs`.
```
The error is same, and I believe it was becasue of the conficts between meme and other libraries. it seems that the meme you specified which was installed with other software in the same environment. Make sure the path of software sepcificed in the configuration file are the ones you wanted. Also please post your configuration file?

**Comment by hchintalapudi** [comment]
So, I was trying to activate the env in my slurm scheduler script:
```source /optnfs/common/miniconda3/etc/profile.d/conda.sh
conda activate cutruntools2```
And I get that error message. However I commented it out and the pipeline runs fine, no issues!

My config file attached.
[bulk-config.json.txt](https://github.com/fl-yu/CUT-RUNTools-2.0/files/6804029/bulk-config.json.txt)

**Comment by fl-yu** [comment]
There is no problem with the configuration.
Can you test if getsize function from meme works? Test this before and after activate meme environment.
/dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/meme/libexec/meme-5.0.2/getsize

**Comment by hchintalapudi** [comment]
```
[f0042dk@discovery7 CutNrun]$ /dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/meme/libexec/meme-5.0.2/getsize
/dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/meme/libexec/meme-5.0.2/getsize: error while loading shared libraries: libicui18n.so.58: cannot open shared object file: No such file or directory
[f0042dk@discovery7 CutNrun]$ conda activate meme
(meme) [f0042dk@discovery7 CutNrun]$ /dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/meme/libexec/meme-5.0.2/getsize
/dartfs-hpc/rc/home/k/f0042dk/miniconda3/envs/meme/libexec/meme-5.0.2/getsize: error while loading shared libraries: libicui18n.so.58: cannot open shared object file: No such file or directory
```
:/

**Comment by fl-yu** [comment]
It seems that the conflicts still exist even you installed the software separately.  I am sorry can not help this further, but you may ask for help from your IT admin to make sure meme works properly.

**Comment by ShikanZ** [comment]
I had the same issue.
 (meme) shikan@shikan-p520:/mnt/Data/Cut_and_tag_nf/docker$ getsize 
getsize: error while loading shared libraries: libicui18n.so.58: cannot open shared object file: No such file or directory

I figured out installing this missing library using conda. First, remove your current meme environment. Then install using this command, conda create -n meme python=3.6 icu=58 meme

Hope it helps!

Shikan

**Comment by hchintalapudi** [comment]
I believe I tried this after looking at some old issues here.
But will work on this again and post an update, thank you @ShikanZ.

**Comment by fl-yu** [comment]
Hi Guys, for meme conflicts, can you try this solution, which I have tested in a clean environment on the cluster.
```
conda create -n meme meme=5.0.5 python=3.7
conda activate meme
```
If you did set the conda channel, run these commands first
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```
Please let me know if this works for you

**Comment by hchintalapudi** [comment]
Hi @fl-yu,
I tried what you suggested above, the other week and still got some errors.
[slurm-138333.out.txt](https://github.com/fl-yu/CUT-RUNTools-2.0/files/6904007/slurm-138333.out.txt)
