### ISSUE TITLE
bowtie2 alignment genome and index config in bulk-pipeline.sh

### ISSUE THREAD

**Issue by mschachter** [fl-yu/CUT-RUNTools-2.0#17]
On lines [52 and 58 of bulk-pipeline.sh](https://github.com/fl-yu/CUT-RUNTools-2.0/blob/master/src/bulk/bulk-pipeline.sh#L54), the index file for bowtie2 alignment is specified as `-x $bt2idx/genome`.

This causes alignment to fail, because there is no index file with the prefix `genome`. I'm using the mm10 reference genome, and the prefix should be `-x $bt2idx/mm10`. Should `genome` be a variable that comes from the config file instead?

**Comment by fentouxungui** [comment]
$bt2idx/genome

should be changed to:

$bt2idx

You can echo $bt2idx to find out what is $bt2idx

**Comment by fl-yu** [comment]
'genome' is not a variable from config. 
This is dependent on your reference genome and index, if you follow the instruction to download and install the reference genome, all the genomes of different species and versions should be called 'genome'. But if you use your own genome files, you need to revise the code, for example, change 'genome' -> 'mm10' in your case.
Hope this helps.

**Comment by mschachter** [comment]
Hi, thanks both for your responses. I'm not sure this bug should have been closed, it's a real bug for people who are not using the downloaded reference genomes. To get it to work, I did something similar to what @fentouxungui suggested.
