### ISSUE TITLE
input sample sequencing data

### ISSUE THREAD

**Issue by mangchen922** [fl-yu/CUT-RUNTools-2.0#18]
Hi, I am a biologist with a limited background in NGS analysis.  And recently I did a bunch of bulk CUT&RUN seq and tried to analyze by myself. So glad to see this pipeline!
In my case, I was using the fragmentase to generate input control for each of my samples, but for this analysis, I don't know where to put this input sequence data. 
Please indicate how to use the input control data and appreciate your response.

Best,
Chen

**Comment by fl-yu** [comment]
Hi Chen
Thank you for your interest in our tool.
Currently, we don't support an input control sample for bulk data processing. As several users requests this feature and I plan to realize it recently, I will open a new section called 'News' to show updates, please stay tuned!
