### ISSUE TITLE
input sample_name

### ISSUE THREAD

**Issue by ShikanZ** [fl-yu/CUT-RUNTools-2.0#19]
Hi,

I have a question. Does this pipeline only read one pair of samples? What if I have multiple samples?

Thanks

**Comment by fl-yu** [comment]
Hi 
The tool only accepts one pair-end sample per run. 
You can put all the fastq files in one folder, then run the bulk pipeline by specifying sample name per run, with the same configuration file if you do not want to change anything except the sample name.
