### ISSUE TITLE
meme problem [solved]

### ISSUE THREAD

**Issue by KQ2012** [fl-yu/CUT-RUNTools-2.0#2]
Hi, fl

I am creating a new issue here, I was able to bypass the bowtie2 index problem by changing the "hg" to "genome". Unfortunately, still having a little problem with the rest of the code. Please see below which I copied directly from my terminal, as there is no error message, however, I did reach the end telling me that the analysis was successful w/o any files in the fimo folder, my symster is MacOS Mojave version 10.14.6 not sure if this information is helpful. Thanks a lot!

[info] Generating the normalized signal file with BigWig format... 
Sun Feb  7 21:47:45 EST 2021
[info] Your bigwig file won't be normalized with spike-in reads
[info] Input file is /Volumes/Backup/CUT-RUNTools-2.0-master/test/GATA1_D7_30min_chr11/peakcalling/macs2.narrow/GATA1_D7_30min_chr11_peaks.narrowPeak
[info] Get randomized [1000] peaks from the top [2000] peaks...
[info] Filtering the blacklist regions for the selected peak files
[info] Getting Fasta sequences
[info] Start MEME analysis for de novo motif finding ...
[info] Up to 10 will be output ...
Log::Log4perl configuration looks suspicious: No loggers defined at /Users/kunhuaqin/miniconda3/envs/meme/lib/site_perl/5.26.2/Log/Log4perl/Config.pm line 325.
Starting getsize: getsize random1000/MEME_GATA1_D7_30min_chr11_shuf/GATA1_D7_30min_chr11_summits_padded.fa 1> $metrics
dyld: Library not loaded: @rpath/libicui18n.58.dylib
  Referenced from: /Users/kq2012/miniconda3/envs/meme/bin/getsize
  Reason: image not found
getsize process died with signal 6, without coredump
getsize failed me... at /Users/kq2012/miniconda3/envs/meme/bin//meme-chip line 740.
[info] De Novo motifs can be found: random1000/MEME_GATA1_D7_30min_chr11_shuf ...
[info] Loading the De Novo motifs ...
Traceback (most recent call last):
  File "/Volumes/Backup/CUT-RUNTools-2.0-master/install/read.meme.py", line 92, in <module>
    ss = read_summary(this_dir + "/summary.tsv")
  File "/Volumes/Backup/CUT-RUNTools-2.0-master/install/read.meme.py", line 7, in read_summary
    f = open(n)
FileNotFoundError: [Errno 2] No such file or directory: 'random1000/MEME_GATA1_D7_30min_chr11_shuf/summary.tsv'
[info] The signficance cutoff of Fimo scaning is 0.0005...
[info] Motif files can be found: random1000/MEME_GATA1_D7_30min_chr11_shuf/motifs
[info] Filtering the blacklist regions for the selected peak files
[info] Getting Fasta sequences
[info] Scaning the De Novo motifs for each peak
ls: random1000/MEME_GATA1_D7_30min_chr11_shuf/motifs: No such file or directory
[info] Output can be found: fimo.result/GATA1_D7_30min_chr11
# 
#        Congrats! The bulk data analysis is complete!

**Comment by fl-yu** [comment]
Hi KQ2012,
Do you see any file generated in the folder `random1000/MEME_GATA1_D7_30min_chr11_shuf`?
If not, it should be the problem of MEME.
These are Error info:
 `dyld: Library not loaded: @rpath/libicui18n.58.dylib
Referenced from: /Users/kq2012/miniconda3/envs/meme/bin/getsize
Reason: image not found
getsize process died with signal 6, without coredump
getsize failed me... at /Users/kq2012/miniconda3/envs/meme/bin//meme-chip line 740.`
Could you check if MEME could work properly?

**Comment by KQ2012** [comment]
YES, MEME is the problem. This was magically solved by removing the old MEME and using:
 conda install 'meme=5.0.2' 'icu=58.2'   (Credit: stackoverflow)

Unfortunately, there is appeared to be some new issues with R, please see below

[info] Doing fimo2.DREME-1.BTTATCW...
2021-02-09 02:18:28,049 INFO Filtering alignments for quality >= 0, with flags [3] and without flags [4, 8]
2021-02-09 02:18:28,049 INFO Using these fragment size bins: [[(25, 150, 1)]]
2021-02-09 02:18:28,050 INFO Reading motifs from fimo.result/GATA1_D7_30min_chr11/fimo2.DREME-1.BTTATCW/fimo.bed...
2021-02-09 02:18:28,050 INFO Making cut point matrix...
2021-02-09 02:18:29,999 INFO Processed 1286 motifs in 1.95s
Error in library(CENTIPEDE) : there is no package called ‘CENTIPEDE’
Execution halted

[info] Doing fimo2.DREME-2.CCCGCCY...
2021-02-09 02:18:30,554 INFO Filtering alignments for quality >= 0, with flags [3] and without flags [4, 8]
2021-02-09 02:18:30,554 INFO Using these fragment size bins: [[(25, 150, 1)]]
2021-02-09 02:18:30,554 INFO Reading motifs from fimo.result/GATA1_D7_30min_chr11/fimo2.DREME-2.CCCGCCY/fimo.bed...
2021-02-09 02:18:30,554 INFO Making cut point matrix...
2021-02-09 02:18:30,912 INFO Processed 279 motifs in 0.36s
Error in library(CENTIPEDE): there is no package called ‘CENTIPEDE’

 I installed the CENTIPEDE and a few more packages in R on my Mac, but it seems a different version is used in this conda env. Any idea?

Another error might be related to this or the "make_cut_matrix" script that we discussed:

Traceback (most recent call last):
  File "/Users/kunhuaqin/.local/bin/make_cut_matrix", line 235, in make_cut_matrix
    for motif_count, (motif, row, tree) in enumerate(results, 1):
  File "/Users/kunhuaqin/.local/bin/make_cut_matrix", line 232, in <genexpr>
    results = (score(motif) for motif in motifs)
  File "/Users/kunhuaqin/.local/lib/python3.6/site-packages/atactk/data.py", line 209, in read_features
    source = open_maybe_gzipped(filename)
  File "/Users/kunhuaqin/.local/lib/python3.6/site-packages/atactk/data.py", line 168, in open_maybe_gzipped
    byte1, byte2 = ord(test_read.read(1)), ord(test_read.read(1))
TypeError: ord() expected a character, but string of length 0 found
Error in library(CENTIPEDE) : there is no package called ‘CENTIPEDE’

Thanks so much!

**Comment by fl-yu** [comment]
Could you check if the path of R (`Rscriptbin`) you specified in the configuration file installed the package CENTIPEDE. It seems that the tool invokes a different R which has no installation of this package.

**Comment by KQ2012** [comment]
The one I specified was not installed with this package. Good Catch! I will update the config file and re-run it. Thanks!
