### ISSUE TITLE
bug fix suggestions on bulk-pipeline

### ISSUE THREAD

**Issue by qiyubio** [fl-yu/CUT-RUNTools-2.0#20]
Hi, I was tesing CutRunTools2 bulk-pipeline, and suggest you to fix some bugs.
1: The file validate.py is wrote in python2, suggest to change it to python3, since that is your conda env based on. Please replace type=file to type=open, and the rest can be fixed by 2to3. 
```
< 	parser.add_argument("config", type=open)
---
> 	parser.add_argument("config", type=file)
 ```
2: The version of meme installed using your command is 5.3.0, also conda needs to run 'conda update --all' to avoid the lack of library error when calling meme/5.3.0:
```
	libicui18n.so.58 => not found
	libicuuc.so.58 => not found
	libicudata.so.58 => not found
```

But your code is based on 5.1.0, -dreme-m is replaced with -streme-nmotifs in 5.3.0. 
```
$memebin/meme-chip -oc $meme_outdir -dreme-m $num_motifs -meme-nmotifs $num_motifs $mpaddedfa/$summitfa
``` 
I changed the code, but then there is error about can't read motif meme.xml. So have you tested if it work on meme/5.3.0?  I'm thinking about rolling back to install meme/5.1.0 instead with "conda install meme=5.1.0". 

3: There is one extra R package was needed. 
```
R -e 'install.packages("viridis")'
```

**Comment by qiyubio** [comment]
Update, downgrade meme to 5.3.0 will still have error since dreme is wrote in python 2.
```
meme ran successfully in 4462.783384 seconds
Starting dreme: dreme -verbosity 1 -oc random1000/MEME_GATA1_D7_30min_chr11_shuf/dreme_out -png -dna -p random1000/MEME_GATA1_D7_30min_chr11_shuf/seqs-centered -n random1000/MEME_GATA1_D7_30min_chr11_shuf/seqs-shuffled -m 10
  File "/opt/conda/envs/meme/bin/dreme", line 765
    print "Finding secondary RE in left flank..."
                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Finding secondary RE in left flank...")?
dreme exited with error code 1
```
I have the same issue as here:
https://github.com/bioconda/bioconda-recipes/issues/1840. So I guess it's better to build the meme env with python2?

**Comment by qiyubio** [comment]
For the single cell pipeline, there is deprecation notice about "igraph", any work around? 
```
Fri Jul 16 18:39:28 2021 [info] Load packages
Deprecation notice
==================

To avoid name collision with the igraph project, the original igraph visualization
library has been renamed to `jgraph` in December 2015. The `igraph` package on
PyPI will soon be used by the igraph project.

The authors of `jgraph` (ex-igraph) and `python-igraph` (soon-to-be igraph)
project have agreed on a transition period during which old projects still
using `igraph` as a PyPI dependency will receive an error while trying to
import igraph in their own projects. The transition period ends on Sep 1 2021.

Things to do now
----------------

If you wanted to install the graph visualization library by Patrick Fuller,
please install `jgraph` instead. You have time until Sep 1 2021 to do this.

If you wanted to install the Python interface of the igraph network analysis
library, please install `python-igraph` instead. After Sep 1 2021, you can
start installing `igraph` instead. `python-igraph` will keep on working at
least until Sep 1 2022.

Error in py_module_import(module, convert = convert) :
  RuntimeError: This package is deprecated. See the deprecation notice above.

Detailed traceback:
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 44, in _import_hook
    level=level
  File "/opt/conda/envs/app/lib/python3.6/site-packages/leidenalg/__init__.py", line 35, in <module>
    from .functions import ALL_COMMS
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 44, in _import_hook
    level=level
  File "/opt/conda/envs/app/lib/python3.6/site-packages/leidenalg/functions.py", line 2, in <module>
    import igraph as _ig
  File "/usr/local/lib/R/site-library/reticulate/python/rpytools/loader.py", line 44, in _import_hook
    level=level
  File "/opt/conda/envs/app/lib/python3.6/site-packages/igraph/__init__.py", line 8, in <module>
    warn_deprecation()
  File "/opt/conda/envs/app/lib/python3.6/site-packages/igraph/_utils.py", line 36, in warn_deprecation
    raise RuntimeError("This package is deprecated.
Calls: suppressPackageStartupMessages ... withCallingHandlers -> <Anonymous> -> py_module_import
Execution halted
#
```

**Comment by fl-yu** [comment]
Hi Thanks so much for your feedback and suggestions!
I will be having tests on the code you mentioned.
For the meme conflicts, which has stuck several other users, can you try these command for py3?
```
conda create -n meme meme=5.0.5 python=3.7
conda activate meme
```

**Comment by fl-yu** [comment]
Can you post more info regarding 'igraph' in the single-cell pipeline? which step do you run into this issue? software installation or run the pipeline

**Comment by qiyubio** [comment]
That version failed too. I found one workaround:

conda create -n meme python=3.6
conda activate meme
conda install ‘meme=5.0.2’ ‘icu=58.2’

> Hi Thanks so much for your feedback and suggestions!
> I will be having tests on the code you mentioned.
> For the meme conflicts, which has stuck several other users, can you try these command for py3?
> 
> ```
> conda create -n meme meme=5.0.5 python=3.7
> conda activate meme
> ```

**Comment by qiyubio** [comment]
Running the pipeline:
```
bash run_scModule.sh sc-config.json
```
Or just:
```
python import igraph
```

The workaround is delete igraph and reinstall python-igraph with conda.

> Can you post more info regarding 'igraph' in the single-cell pipeline? which step do you run into this issue? software installation or run the pipeline

**Comment by qiyubio** [comment]
Also another bug in Rscript line 103, shouldn't be just tfidf2.rda?
https://github.com/fl-yu/CUT-RUNTools-2.0/blob/d3607052693c4d364b3b873278c837d581d33f91/src/Rscript/scmatrix_analysis_pipeline.r#L103

**Comment by qiyubio** [comment]
And there is space before line end on line 21 and 26 of patch file, which will give errors:
```patch unexpectedly ends in middle of line``` when running ```patch -p0 -N --dry-run --silent metrics.py < metrics.py.patch 2> /dev/null```. 

The patch works after remove those spaces. Just post it here in case other people have similar problem.

https://github.com/fl-yu/CUT-RUNTools-2.0/blob/d3607052693c4d364b3b873278c837d581d33f91/install/metrics.py.patch#L21
https://github.com/fl-yu/CUT-RUNTools-2.0/blob/d3607052693c4d364b3b873278c837d581d33f91/install/metrics.py.patch#L26

**Comment by fl-yu** [comment]
Thank you so much qiyubio!! All the issues were fixed.
Please feel free to post any issues/bugs. You may consider using the Pull requests function for the issues or new features which were useful as I am more than happy to highlight others' contributions by listing them as contributors.

**Comment by qiyubio** [comment]
Thanks for fixing the bugs! 
I created a singularity definition file for others to easily install CutRunTools2 on their HPC cluster:
https://github.com/qiyubio/CutRunTools2_singularity/blob/main/CutRunTools2.def

**Comment by Super1991** [comment]
> eme=5.0

I also had the same problem, after trying both of your solutions by re-installing the meme. But for me, I only had problems when running dreme; but meme, fimo worked fine.

dreme
  File "~/miniconda/envs/meme/bin/dreme", line 765
    print "Finding secondary RE in left flank..."
                                                ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Finding secondary RE in left flank...")?

As suggested by meme-suite authors, one should use "dreme-py3", instead of "dreme" written in python2.
https://meme-suite.org/meme/doc/dreme.html

Thank you guys for developing this amazing tool! Appreciate it!

Best
Jingchao

**Comment by fl-yu** [comment]
Hi Super1991, thanks for using our tool. I did not encounter this issue. 
MEME is always the tricky part. Can you try python2 rather than python3 to see if the issue insists?

**Comment by thugib** [comment]
Thank you very much for the reply and the link. I will look it over and see if it will solve the problem.  I am getting a lot of dependency conflicts. If I use python 3.9 there are problems. If I use python 3.6 and all the versions for macs2, deeptools, etc. listed on the CutnRunTools installation page, then with libmamba as solver, there are many version conflicts, as well packages no longer exist. chatGPT is telling me to force conda to use full repodata.json, use the classic conda solver, not libmamba, clean the cache and try again to create the environment with all the specific versions, but there are many, many conflicts and it is unable to install the packages.
