### ISSUE TITLE
gff2bed: line 132: convert2bed: command not found

### ISSUE THREAD

**Issue by ShikanZ** [fl-yu/CUT-RUNTools-2.0#21]
Hi,

I am running this pipeline. MEME is working based on your previous discussion with @qiyubio. However, I have got this error. 
/home/shikan/miniconda3/envs/cutruntools2/bin/gff2bed: line 132: convert2bed: command not found
I have checked under my cutruntools2 conda environment, gff2bed and conver2bed are existing. How do I fix this issue.

Thanks,
Shikan

**Comment by fl-yu** [comment]
Great!
Can you try to add 'bin' directory into PATH before running the pipeline? e.g. 
export PATH="/home/shikan/miniconda3/envs/cutruntools2/bin:$PATH"

**Comment by ShikanZ** [comment]
I ran the command under cutruntools2 environment and it worked! Thanks!
