### ISSUE TITLE
Spikein_scale

### ISSUE THREAD

**Issue by ShikanZ** [fl-yu/CUT-RUNTools-2.0#22]
Hi,

I have a question about spikein_scale. I have a cut_and_tag data that do not have spike-in genome. Also, for spike_in_align and spike_in_norm, I chose false. I see that the spikein_scale equation is spikein_scale/spikein_reads. How is the data normalized, if I don't have any spike_in reads?

Thanks,
Shikan

**Comment by fl-yu** [comment]
Do not worry about it as it will not run the spike-in norm if you set false to spike_in_norm. For the resulting bigwig files, we will perform CPM normalization if you do not have spike-in reads for normalization.
