### ISSUE TITLE
spike_in: "TRUE"

### ISSUE THREAD

**Issue by ec10715** [fl-yu/CUT-RUNTools-2.0#23]
Hi, I've been trying to normalize with spike in, setting "spike_in": "TRUE". This doesn't seem to work however, and there is no spike_in output directory created. 

Should I be setting "spike_in" as TRUE? or something else?

**Comment by fl-yu** [comment]
If you would like to perform spike-in norm, make sure that:
you have valid setting of `"spike_in_bt2idx"` and `"spike_in_sequence"`, and specify `"spike_in"` and `"spike_in_norm"` as "TRUE" in the meantime

**Comment by ec10715** [comment]
There is a discrepancy in bulk-config.json and bulk-pipeline.sh that can be corrected by editing bulk-pipeline.sh

In bulk-config.json "spike_in" is used, however bulk-pipeline.sh uses "spike_in_align". If you edit bulk-pipeline.sh to read "spike_in" rather than "spike_in_align" this fixes the problem.

**Comment by fl-yu** [comment]
Good catch! Thank you for your feedback!
