### ISSUE TITLE
advice on some features 

### ISSUE THREAD

**Issue by dcruz5h** [fl-yu/CUT-RUNTools-2.0#24]
Thank you for all the work you put on this pipeline. 
I hope you can help me define some parameters. I am running the pipeline for bulk Cut and Tag samples that were  sequenced pairs end with 150Cycle kit. 
What would the fastq_sequence_length be?
 
What does frag_120 do ? if you do FALSE what happens to the bam file ? and if you do TRUE what happens ?
The initial step of adaptor trimming, trimomatic assumed my fastq files had Truseq adapters even after I specify CUT&Tag as the experiment_type. How can I change trimomatic to remove Nextera adaptors instead ?

**Comment by fl-yu** [comment]
Hi @dcruz5h Thanks for your interest in our tool!
I do not know what the sequence length will be for 150Cycle kit. But I think it is ok if the read length is longer than 25bp as our two-step trimming will eventually trim all the reads to 25bp and we show that this trimming strategy is able to improve reads alignment.
If you specify frag_120 as TRUE, the bam file will rule out the fragments longer than 120, we recommend it when you do a typical TF experiment.
```
[frag_120]: Whether filter the bam files based on the criteria of fragment size 120
			options: TRUE (default) or FALSE 
```
Currently, we only support Truseq adapters. I can add a new parameter to support trimming with the Nextera adaptors later.

**Comment by dcruz5h** [comment]
Thank you for the answer. It will be great if you can add an option for Nextera adaptors as bulk CUT$Tag works with these adaptors and not Truseq.

**Comment by fl-yu** [comment]
Hi, we have already supported the Nextera adaptors processing with the bulk data, please update the software to the least. Please let me know if you encounter any trouble with this. 

Usage:
In the new configuration file, you could value `adaptor_type` as `Truseq` or `Nextera` to specify your adaptor type.
`"adaptor_type":"Truseq"` or
`"adaptor_type":"Nextera"`

**Comment by dcruz5h** [comment]
Thank you !! I just finish running  it and it now trims neuter adaptors. It is able to generate bam files as well as bed files. 
Cheers

**Comment by fl-yu** [comment]
Awesome! I will close this thread, please feel free to open new issues if you run into any issues.
