### ISSUE TITLE
Can`t run the software at the beginning

### ISSUE THREAD

**Issue by jamesc99** [fl-yu/CUT-RUNTools-2.0#29]
Hey, I am using the CUT-RUNTools2.0 to do some tests and I encountered some problems at the beginning. I think I correctly all the required softwares and correctly set them in the bulk-config.json file. And I got an empty line following your guide which means the validate.py script runs without errors. However, when I try to do the bulk analysis, there is an error. Here is my code and error:
codes:
./run_bulkModule.sh bulk-config.json SRR891269
error:
./run_bulkModule.sh: line 89: /home/ryan/controlsoftware/CUT-RUNTools-2.0-master/install2/src/bulk/bulk-pipeline.sh: No such file or directory
I checked the installation directory where there was no such file or directory. 

Do you have any idea about these issue? I would be really appreciate that if you could give me some advice. Thanks very much!
Ryan,

**Comment by fl-yu** [comment]
Hi Ryan,

it seems that a `install2` is the issue in `/home/ryan/controlsoftware/CUT-RUNTools-2.0-master/install2/src/bulk/bulk-pipeline.sh`. can you check the directory you run the tool with `pwd`?
