### ISSUE TITLE
Unable to find validate.py

### ISSUE THREAD

**Issue by CriticalPeriod** [fl-yu/CUT-RUNTools-2.0#3]
Dear team of CUT RUN tools 2.0

I'm trying to use your software to analyze my CR data. I'm running on MacOS Big Sur. 
I created the conda env, managed the dependancies, ddl and build the index. However, I'm not able to find the validate.py script. 
I did find it in the previous version of the program, but it doesn't seem to work with crtools2.0
I followed strictly the instructions in install.md after I cloned your repository. 
I set all the variables in the json file. 

Can you add a little precision on how I can validate the installation before pursuing ? 

Thank you very much, 
David 

here's my env. my shell is zsh. 

(cutruntools2.1) XXX@XXX CUT-RUNTools-2.0 % conda list    
# packages in environment at /Users/XXX/miniconda3/envs/cutruntools2.1:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.1               anacondar_1    conda-forge
bedops                    2.4.39               h770b8ee_0    bioconda
bedtools                  2.30.0               haa7f73a_1    bioconda
bowtie2                   2.4.2            py36h6343656_2    bioconda
bwidget                   1.9.14               h694c41f_0    conda-forge
bzip2                     1.0.8                h0d85af4_4    conda-forge
c-ares                    1.17.1               h0d85af4_1    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
cairo                     1.16.0            he43a7df_1008    conda-forge
cctools_osx-64            949.0.1             h6407bdd_21    conda-forge
certifi                   2020.12.5        py36h79c6626_1    conda-forge
clang                     11.1.0               h694c41f_0    conda-forge
clang-11                  11.1.0          default_he082bbe_0    conda-forge
clang_osx-64              11.1.0               hb91bd55_1    conda-forge
clangxx                   11.1.0          default_he082bbe_0    conda-forge
clangxx_osx-64            11.1.0               h7e1b574_1    conda-forge
compiler-rt               11.1.0               h654b07c_0    conda-forge
compiler-rt_osx-64        11.1.0               h8c5fa43_0    conda-forge
curl                      7.76.1               h06286d4_1    conda-forge
cycler                    0.10.0                     py_2    conda-forge
deeptools                 3.5.1                      py_0    bioconda
deeptoolsintervals        0.1.9            py36ha714b87_3    bioconda
expat                     2.2.10               h1c7c35f_0    conda-forge
fontconfig                2.13.1            h10f422b_1005    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
fribidi                   1.0.10               hbcb3906_0    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
gfortran_impl_osx-64      9.3.0               h9cc0e5e_22    conda-forge
gfortran_osx-64           9.3.0               h18f7dce_14    conda-forge
ghostscript               9.18                          1    bioconda/label/cf201901
gmp                       6.2.1                h2e338ed_0    conda-forge
graphite2                 1.3.13            h2e338ed_1001    conda-forge
gsl                       2.6                  h71c5fe9_2    conda-forge
harfbuzz                  2.8.0                h159f659_1    conda-forge
htslib                    1.12                 hc38c3fb_1    bioconda
icu                       68.1                 h74dc148_0    conda-forge
isl                       0.22.1               hb1e8313_2    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
kiwisolver                1.3.1            py36h615c93b_1    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
lcms2                     2.12                 h577c468_0    conda-forge
ld64_osx-64               530                 he8994da_21    conda-forge
ldid                      2.1.2                h7660a38_2    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libclang-cpp11.1          11.1.0          default_he082bbe_0    conda-forge
libcurl                   7.76.1               h8ef9fac_1    conda-forge
libcxx                    11.1.0               habf9029_0    conda-forge
libdeflate                1.7                  h35c211d_5    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_22    conda-forge
libgfortran-devel_osx-64  9.3.0               h6c81a4c_22    conda-forge
libgfortran5              9.3.0               h6c81a4c_22    conda-forge
libglib                   2.68.1               hd556434_0    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
libllvm11                 11.1.0               hd011deb_2    conda-forge
libnghttp2                1.43.0               h07e645a_0    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libssh2                   1.9.0                h52ee1ee_6    conda-forge
libtiff                   4.2.0                h355d032_0    conda-forge
libwebp-base              1.2.0                h0d85af4_2    conda-forge
libxml2                   2.9.10               h93ec3fd_4    conda-forge
libxslt                   1.1.33               h5739fc3_2    conda-forge
llvm-openmp               11.1.0               hda6cdc1_1    conda-forge
llvm-tools                11.1.0               hd011deb_2    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
macs2                     2.2.7.1          py36ha714b87_2    bioconda
make                      4.3                  h22f3db7_1    conda-forge
matplotlib-base           3.3.4            py36h4ea959b_0    conda-forge
meme                      4.12.0          py36pl526hd869df4_2    bioconda/label/cf201901
mpc                       1.1.0             ha57cd0f_1009    conda-forge
mpfr                      4.0.2                h72d8aaf_1    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
numpy                     1.19.5           py36h08dc641_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h6cbf5cd_0    conda-forge
openssl                   1.1.1k               h0d85af4_0    conda-forge
pango                     1.48.4               ha05cd14_0    conda-forge
parallel                  20210222             h694c41f_0    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pcre2                     10.36                h5cf9962_1    conda-forge
perl                      5.26.2            hbcb3906_1008    conda-forge
perl-app-cpanminus        1.7044                  pl526_1    bioconda/label/cf201901
perl-carp                 1.38                    pl526_1    bioconda/label/cf201901
perl-cgi                  4.40            pl526h470a237_0    bioconda/label/cf201901
perl-constant             1.33                    pl526_1    bioconda/label/cf201901
perl-exporter             5.72                    pl526_1    bioconda/label/cf201901
perl-extutils-makemaker   7.34                    pl526_3    bioconda/label/cf201901
perl-file-path            2.15                    pl526_0    bioconda/label/cf201901
perl-file-temp            0.2304                  pl526_2    bioconda/label/cf201901
perl-html-parser          3.72            pl526h2d50403_4    bioconda/label/cf201901
perl-html-tagset          3.20                    pl526_3    bioconda/label/cf201901
perl-html-template        2.97                    pl526_1    bioconda/label/cf201901
perl-html-tree            5.07                    pl526_0    bioconda/label/cf201901
perl-parent               0.236                   pl526_1    bioconda/label/cf201901
perl-scalar-list-utils    1.45            pl526h470a237_3    bioconda/label/cf201901
perl-xml-namespacesupport 1.12                    pl526_0    bioconda/label/cf201901
perl-xml-parser           2.44            pl526h3a4f0e9_6    bioconda/label/cf201901
perl-xml-sax              1.00                    pl526_0    bioconda/label/cf201901
perl-xml-sax-base         1.09                    pl526_0    bioconda/label/cf201901
perl-xml-sax-expat        0.51                    pl526_2    bioconda/label/cf201901
perl-xml-simple           2.25                    pl526_0    bioconda/label/cf201901
perl-xsloader             0.24                    pl526_0    bioconda/label/cf201901
perl-yaml                 1.27                    pl526_0    bioconda/label/cf201901
pillow                    8.1.2            py36h154fef6_1    conda-forge
pip                       21.0.1             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
plotly                    4.14.3             pyh44b312d_0    conda-forge
py2bit                    0.3.0            py36ha714b87_5    bioconda
pybigwig                  0.3.18           py36hc3e6b37_1    bioconda
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pysam                     0.16.0.1         py36h71aea8d_3    bioconda
python                    3.6.13          h7728216_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.6                     1_cp36m    conda-forge
r-base                    4.0.3                hb6e1b8c_8    conda-forge
readline                  8.1                  h05e3726_0    conda-forge
retrying                  1.3.3                      py_2    conda-forge
samtools                  1.12                 hfcfc997_1    bioconda
scipy                     1.5.3            py36h04de62b_0    conda-forge
setuptools                49.6.0           py36h79c6626_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.35.4               h44b9ce1_0    conda-forge
tabix                     0.2.6                ha92aebf_0    bioconda
tapi                      1100.0.11            h9ce4665_0    conda-forge
tbb                       2020.2               h940c156_4    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tktable                   2.10                 h49f0cf7_3    conda-forge
tornado                   6.1              py36h20b66c6_1    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.9                h582d3a0_0    conda-forge

**Comment by fl-yu** [comment]
Hi David,

Can you check if validate.py script is in your 'install' folder? 
Otherwise, you can download one 
https://github.com/fl-yu/CUT-RUNTools-2.0/blob/master/install/validate.py

**Comment by hejing3283** [comment]
> Hi David,
> 
> Can you check if validate.py script is in your 'install' folder?
> Otherwise, you can download one
> https://github.com/fl-yu/CUT-RUNTools-2.0/blob/master/install/validate.py

Hi fulong,
it seems this python script was written in python 2.x. Am I right?  
When I try to run it, it throws out errors. 
-----------------
  File "validate.py", line 19
    print program, "is not found in", path
------------------------

**Comment by AndrewC160** [comment]
Just to append to this issue with validate.py, I receive Python errors when running it:

`TabError: inconsistent use of tabs and spaces in indentation`

This error appears to be exactly what it says; I went into validate.py and replaced the indentation in module_exists().
