### ISSUE TITLE
Alignment Error

### ISSUE THREAD

**Issue by jamesc99** [fl-yu/CUT-RUNTools-2.0#30]
Hey,

I am trying to run CUTRUNTools2.0 to test cut&run data and I have downloaded all the required software and make the bulk-config.json file right. Actually I could run the test but I always get the error at the alignment part, it will shows The bulk data analysis is complete but the output file is empty. And I put the error below.

I have tried several times and tried to modify the config file and adjust the environment, but all ddidn`t work. 

Look forward to your advice,
Ryan

#the errors are listed below

**[info] FASTQ files won't be aligned to the spike-in genome

IOError: [Errno 2] No such file or directory: '/home/ryan/controlsoftware/cut_run_tag/fastq_directory_for_tool/output_cutruntools2.0/test1/peakcalling/seacr/test1_treat_pileup.bdg'
Calling enriched regions without control file
Proceeding without normalization of control to experimental bedgraph

IOError: [Errno 2] No such file or directory: '/home/ryan/controlsoftware/cut_run_tag/fastq_directory_for_tool/output_cutruntools2.0/test1/peakcalling/seacr/test1_treat.stringent.bed'

SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Finding secondary RE in left flank...")?
dreme exited with error code 1

IOError: [Errno 2] No such file or directory: 'random1000/MEME_test1_shuf/dreme_out/dreme.txt'**

**Comment by fl-yu** [comment]
Hi Ryan
I wonder is there any correct bam file generated? I can not figure out the issue that occurs in which step

**Comment by jamesc99** [comment]
> Hi Ryan
> I wonder is there any correct bam file generated? I can not figure out the issue that occurs in which step

Hi,

yes, the problem is that the generated bam file is empty. I think I have configured the json file correctly. Do you have any advice? Thanks

**Comment by jjz46** [comment]
Hi James I am having the same issue with an empty bam file being generated. How did you fix this issue?
