### ISSUE TITLE
No read in trimmed2 can align to the reference genome

### ISSUE THREAD

**Issue by yannnnLi** [fl-yu/CUT-RUNTools-2.0#34]
Hi Fulong,
  I am a PHD student of Prof. Liu nan, one of the co-authors of CUT&RUNtools 1.0. For testing whether the CUT&RUNtools 2.0 work, I downloaded the pair-end FASTQ file (GSE104550, 25bp per end) from the assays of H3K27me3 CUT&RUN. I disabled the frag_120 parameter ("frag_120": "FALSE",). Then I ran the bulk pipeline and found that there is no read in trimmed2 can be aligned to the reference: hg19. Additionally, I aligned the reads in the trimmed2 to ref genome manually and there is no alignment too. However, I found that if I remove the parameter "--very-sensitive-local", there would be some expected results. So, could you give some advice to me for this problem? I am looking forward your response.
Yan
![image](https://user-images.githubusercontent.com/46277338/147904866-6b835b34-cf81-424d-82d5-584bc88015f2.png)
![image](https://user-images.githubusercontent.com/46277338/147905454-822c82b3-eaa4-42a2-9f29-5deb1892d712.png)

**Comment by fl-yu** [comment]
Hi Yan

I wonder how much data you have before and after you trimmed the data. In general, the '--very-sensitive-local' mode will not have a very big effect on your alignment. 
Does it seem correct of the resulting bam files after you remove the '--very-sensitive-local'? Have you tested the other dataset?

**Comment by yannnnLi** [comment]
There are ~ 23.5, 18.4, 18.4 million reads in raw, trimmed and trimmed2 FASTQ data, respectively.
When I align raw reads and paired reads in trimmed with "--very-sensitive-local", It seems correct of resulting bam. However, "--very-sensitive-local" is not useful for reads in trimmed2 and the result seems correct after removing this parameter.
I have tested the example data of GATA1 CUT&RUN assays and this dataset is the first dataset for detecting histone motification. I will download and test other dataset.
Yan
![image](https://user-images.githubusercontent.com/46277338/147996091-e9883a21-2f4c-44cd-88bc-4151d6c7298a.png)
![image](https://user-images.githubusercontent.com/46277338/147996135-eb3fd16c-e946-4840-9bae-ca053f70a5cd.png)
![image](https://user-images.githubusercontent.com/46277338/147996337-307c6b38-fa6b-4a33-89ce-c7ccb3ee61b6.png)
![image](https://user-images.githubusercontent.com/46277338/147996522-59438814-9450-49d2-8533-d752da6c02eb.png)

**Comment by yannnnLi** [comment]
Notably, the paired reads in trimmed directory are with the length of 25 bp, whereas the reads in trimmed2 directory are with the length of 19 bp. Mapping the paired reads in trimmed with "--very-sensitive-local" returns correct result in SAM format.

**Comment by yannnnLi** [comment]
Hello, Fulong, 
I have tested the other dataset of CUT&Tag assays of H3K27me3 modification (GSE192965, PE: 150bp) and got correct result. Maybe the short length of reads impact the right mapping.
Yan

**Comment by fl-yu** [comment]
That might be the case. Thank you for your updates, Yan!
