### ISSUE TITLE
validate.py throws TabError with python3.6.0, replaced tabs with spaces

### ISSUE THREAD

**Issue by kindln** [fl-yu/CUT-RUNTools-2.0#36]
Hello, while attempting to run the validate.py script in the installs directory with python 3.6.0, I got this tab error:
```
  File "/opt/CUT-RUNTools-2.0/install/validate.py", line 28
    return False
               ^
TabError: inconsistent use of tabs and spaces in indentation
```
I was able to fix it with this sed command to replace each tab with 4 spaces:
```
sed -i 's/\t/    /g' validate.py
```
Hope this is helpful. 
Thanks,
Neil

**Comment by fl-yu** [comment]
Thank you for your feedback, Neil! This is helpful!
