### ISSUE TITLE
About filteration of fragmeng length and reads shifting

### ISSUE THREAD

**Issue by yannnnLi** [fl-yu/CUT-RUNTools-2.0#37]
Hi, Fulong
As expect, after reads shifting mapping result of CUT&Tag, the fragment length will reduced 9bp, thus there are fragments less than 120bp (frag_120=TRUE). I readed the code of bulk-pipeline.sh and was interested in why CUT&RUNTools2 filter fragmeng length before shifting instead of after reads shifting. Actually, the fragment after shifting is the real fragment, right?
Yan

**Comment by fl-yu** [comment]
Hi Yan Thank you for using CUT&RUNTools2!
You are right about the reads shifting about CUT&Tag data. This may cause some fragments that are actually shorter than 120 but longer than 120 before reads shifting to be filtered out, precisely those fragments (120-129) before reads shifting. The 120 bp filtration is kind of arbitrary and I figure this should be little effect on the following analysis. Thank you for pointing this out! I will work on adjusting the script later on.

**Comment by yannnnLi** [comment]
Thanks for your response. The answer does answer my question.
