### ISSUE TITLE
`jq` not listed as dependency

### ISSUE THREAD

**Issue by quantumdot** [fl-yu/CUT-RUNTools-2.0#40]
My university cluster system did not have `jq` command installed. It was easy to install myself, but you should note this as a dependency in the install instructions.

**Comment by ChristianRohde** [comment]
Hi, I also got stuck on missing jq on my fresh HPC installation. I never heard about this software so I needed to find this closed issue first. I solved this issue by installing jq into the enviroment cutruntools2.1. Maybe you can just add this to the yml.

Best,
Christian
