### ISSUE TITLE
Can CUT-RUNTools be used with Arabidopsis ?

### ISSUE THREAD

**Issue by thugib** [fl-yu/CUT-RUNTools-2.0#41]
I am using the Arabidopsis bowtie2 index and the Arabdiopsis genome.fa and have the correct paths to these files in my bulk-config.json file, but when I run it, it quickly stops with just the error message: organism_build should be one of hg38, hg19, mm10 or mm9. 
      Is it possible to run CUT-RUNTools with Arabidopsis ?

  I found a blacklist for Arabidopsis, and I can make a chromosome sizes file. If I tweak the run_bulkModule.sh script to use these files, would this work, or are there any other issues that would come up ?

**Comment by fl-yu** [comment]
Sorry, we currently only support human and mouse data processing and analysis! Yes you are definitely could modify the run_bulkModule.sh at several spots and replace the needed files corresponding. Please let me know if you encounter any issues. Also, please cite our paper if you find it useful! Thank you!
Yu et al., CUT&RUNTools 2.0: a pipeline for single-cell and bulk-level CUT&RUN and CUT&Tag data analysis, Bioinformatics, 2021 [PubMed](https://pubmed.ncbi.nlm.nih.gov/34244724/).
