### ISSUE TITLE
KSEQ trouble

### ISSUE THREAD

**Issue by itstomfrancis** [fl-yu/CUT-RUNTools-2.0#43]
when running KSEQ on paired-end fastq files with a read length of 150 that have already been trimmed by trimmomatic i am getting an output of fastq files where a majority of reads have a length of 50bp. Is this right? apologies as this is my introduction to any form of RNA sequencing pipelines.

**Comment by fl-yu** [comment]
Hi Thank you for your interest in our software!

I think it should be fine to use the data that has been trimmed as input, as the alignment is really dependent on the first a few dozen sequences of read pairs.
