### ISSUE TITLE
Questions about process debugging

### ISSUE THREAD

**Issue by songrunxian** [fl-yu/CUT-RUNTools-2.0#44]
Dear professor,

I tried to debug the run_bulkModule using ExampleData.
my config.json is:

        "bt2idx": "/histor/sun/wangtao/0_user/6_maofb/cutrun/0.workplace/1.ref/Homo_sapiens/index", 
        "genome_sequence": "/histor/sun/wangtao/0_user/6_maofb/cutrun/0.workplace/1.ref/Homo_sapiens/Homo_sapiens.GRCh38.dna.toplevel.fa.gz", 
        "spike_in_bt2idx": "/histor/sun/wangtao/0_user/6_maofb/cutrun/CUT-RUNTools-2.0/ensemble/index", 
        "spike_in_sequence": "/histor/sun/wangtao/0_user/6_maofb/cutrun/CUT-RUNTools-2.0/ensemble/Escherichia_coli_str_k_12_substr_mg1655_gca_000005845.ASM584v2.dna.chromosome.Chromosome.fa", 

and my result is :
[info] Input file is GATA1_D7_30min_chr11_R1_001.fastq.gz and GATA1_D7_30min_chr11_R2_001.fastq.gz
星期三 五月  4 22:28:40 CST 2022
[info] Trimming file GATA1_D7_30min_chr11 ...
星期三 五月  4 22:28:40 CST 2022
[info] Use Truseq adaptor as default 
[info] Second stage trimming GATA1_D7_30min_chr11 ...
星期三 五月  4 22:28:40 CST 2022
[info] Aligning file GATA1_D7_30min_chr11 to reference genome...
星期三 五月  4 22:28:40 CST 2022
[info] Bowtie2 command: --dovetail --phred33
[info] The dovetail mode is enabled [as parameter frag_120 is on]
[main_samview] fail to read the header from "-".
[info] FASTQ files won't be aligned to the spike-in genome
[info] Filtering unmapped fragments... GATA1_D7_30min_chr11.bam
星期三 五月  4 22:28:41 CST 2022
[main_samview] fail to read the header from "/histor/sun/wangtao/0_user/6_maofb/cutrun/CUT-RUNTools-2.0/exampleData/bulk-example-test/GATA1_D7_30min_chr11/aligned/GATA1_D7_30min_chr11.bam".
[info] Sorting BAM... GATA1_D7_30min_chr11.bam
星期三 五月  4 22:28:41 CST 2022

I really do not know why about this ?
[main_samview] fail to read the header from "-".

**Comment by fl-yu** [comment]
Hi thank you for your interest in our software!

It seems that you did not have a correct configuration at least for `bt2idx` and `genome_sequence`. You should specify `genome_sequence` as FASTA file of reference genome, usually suffix with .fa. Can you show what you have in the directory '/histor/sun/wangtao/0_user/6_maofb/cutrun/0.workplace/1.ref/Homo_sapiens/index'?

It could be easier if you follow our instructions for downloading the reference genome [part 5](https://github.com/fl-yu/CUT-RUNTools-2.0/blob/master/docs/INSTALL.md).

**Comment by songrunxian** [comment]
Oh thanks Sir . I will try

**Comment by songrunxian** [comment]
> Hi thank you for your interest in our software!
> 
> It seems that you did not have a correct configuration at least for `bt2idx` and `genome_sequence`. You should specify `genome_sequence` as FASTA file of reference genome, usually suffix with .fa. Can you show what you have in the directory '/histor/sun/wangtao/0_user/6_maofb/cutrun/0.workplace/1.ref/Homo_sapiens/index'?
> 
> It could be easier if you follow our instructions for downloading the reference genome [part 5](https://github.com/fl-yu/CUT-RUNTools-2.0/blob/master/docs/INSTALL.md).

Professor, I've had common sense for a long time and it hasn't worked, okay.
in my configure.json:

bt2idx": "/histor/sun/wangtao/0_user/6_maofb/cutrun/CUT-RUNTools-2.0/install/assemblies/hg38/Bowtie2Index",
"genome_sequence": "/histor/sun/wangtao/0_user/6_maofb/cutrun/CUT-RUNTools-2.0/install/assemblies/hg38/hg38.fa",
"spike_in_bt2idx": "/histor/sun/wangtao/0_user/6_maofb/cutrun/CUT-RUNTools-2.0/ensemble/Bowtie2Index",                                             
"spike_in_sequence": "/histor/sun/wangtao/0_user/6_maofb/cutrun/CUT-RUNTools-2.0/ensemble/Escherichia_coli_str_k_12_substr_mg1655_gca_000005845.ASM584v2.dna.chromosome.Chromosome.fa",


and in these pathway we can see that :
/histor/sun/wangtao/0_user/6_maofb/cutrun/CUT-RUNTools-2.0/install/assemblies/hg38:
drwxr-xr-x   6 wangtao sun       4096 2022-05-06 15:13 Bowtie2index
-rw-r--r--   1 wangtao sun        150 2022-05-06 13:55 bowtie.sh
-rw-r--r--   1 wangtao sun  510918613 2022-05-06 13:55 chromFaMasked.tar.gz
-rw-r--r--   1 wangtao sun 3273481150 2022-05-06 13:55 hg38.fa
-rw-r--r--   1 wangtao sun      19304 2022-05-06 14:22 hg38.fa.fai
drwxr-xr-x 219 wangtao sun      16384 2022-05-06 13:55 maskedChroms
-rw-------   1 wangtao sun      16801 2022-05-06 13:55 nohup.out

/histor/sun/wangtao/0_user/6_maofb/cutrun/CUT-RUNTools-2.0/ensemble
drwxr-xr-x 6 wangtao sun    4096 2022-05-06 15:36 Bowtie2Index
-rw-r--r-- 1 wangtao sun      59 2022-05-04 22:02 bowtie.sh
-rw-r--r-- 1 wangtao sun 4719087 2022-02-15 19:12 Escherichia_coli_str_k_12_substr_mg1655_gca_000005845.ASM584v2.dna.chromosome.Chromosome.fa

and the result is still : 
[info] Second stage trimming GATA1_D7_30min_chr11 ...
星期五 五月  6 15:39:22 CST 2022
[info] Aligning file GATA1_D7_30min_chr11 to reference genome...
星期五 五月  6 15:39:22 CST 2022
[info] Bowtie2 command: --dovetail --phred33
[info] The dovetail mode is enabled [as parameter frag_120 is on]
[main_samview] fail to read the header from "-".
[info] FASTQ files won't be aligned to the spike-in genome
[info] Filtering unmapped fragments... GATA1_D7_30min_chr11.bam

this let me can not generate GATA1_D7_30min_chr11.bam file

**Comment by fl-yu** [comment]
Do the trimmed files generate correctly?

**Comment by songrunxian** [comment]
> Do the trimmed files generate correctly?

I think it is wrong . in fact i still very curious, my dear professor . Because at this we set the False at here:
 
![1651886013(1)](https://user-images.githubusercontent.com/49523415/167232104-af46aafc-efb4-49ae-bc81-ff3ab15eb1e2.png)

but why the note is still like this?
![1651886149(1)](https://user-images.githubusercontent.com/49523415/167232170-b76d22f0-32c1-486e-9373-99d61b376fdd.png)
our bam is nothing because the bowtie with spike-in genome is wrong

and my bulk_data_config.json is like this :
![1651886288(1)](https://user-images.githubusercontent.com/49523415/167232236-292250f0-04f9-4bef-9bad-741879d9be5f.png)
Students would like to have your advice if the professor is available

**Comment by songrunxian** [comment]
Oh i find a new question ,professor. that what is extratools in /CUT-RUNTools-2.0/install:
![1651940788(1)](https://user-images.githubusercontent.com/49523415/167263209-4227e61b-dc73-42c6-a045-916a95d207f0.png)

**Comment by fl-yu** [comment]
I will close this thread but please feel free to reopen it if you have questions.
