### ISSUE TITLE
Questions about motif discovery section under bulk-pipeline.sh

### ISSUE THREAD

**Issue by mk1209567** [fl-yu/CUT-RUNTools-2.0#45]
Hi,

First of all, thank you for sharing the pipeline! I'm new to this analysis and this pipeline helps me a lot.

I've been running this pipeline section by section. While running the motif discovery section in bulk-pipeline.sh, I found that 'num_peaks' and 'total_peaks' don't seem to be assigned in the script. I was wondering if they're missing or are they somewhere in the pipeline that I missed?

Thank you!

**Comment by fl-yu** [comment]
Hi Thank you for finding our software helpful!
Basically, those are two integer values. We reasoned that only a fraction of top significant peaks is useful for motif analysis. By default, we will the peaks with adj P values and use 'num_peaks' peaks in the top 'total_peaks' significant peaks for denovo motif discovery.
