### ISSUE TITLE
inquire about trim adapter

### ISSUE THREAD

**Issue by jamesc99** [fl-yu/CUT-RUNTools-2.0#49]
Hi,

I am using CRTool and I wanna give my thanks to you for developing such great software!

But I do have a question about the adapter. **How did you choose the adapter for CUT&RUN, CUT&Tag data?** is there any doc/paper that recommends it? I am using *cutadapt* to mimic your analysis process and wondering which adapter should I use, I notice there are plenty of adapters in your dir.

If you do have some universal adapter specifically for CUT&Tag-seq data, please let me know! really appreciate!

Thanks for your time and help!

Ryan

**Comment by fl-yu** [comment]
Hi Ryan, Thank you for using our tool!

As far as I know, the adaptor corresponds to the library kit you used for your CUT&Tag data. We added a parameter for adaptor use in configure file and the document can be found [here](https://github.com/fl-yu/CUT-RUNTools-2.0/issues/24). By default, `Truseq` will be used, which I think it should be a general adapter sequence. 

Please let me know if you have any other questions!

**Comment by fl-yu** [comment]
I will close this thread but please feel free to reopen it if you have questions.
