### ISSUE TITLE
Conda environment documentation reports inconsistent versions

### ISSUE THREAD

**Issue by rmarable** [fl-yu/CUT-RUNTools-2.0#54]
There is a discrepancy in the documentation with the versioning of the Conda environment referenced in the example JSON configuration files.

In `install/environment1.yml`, the environment is named `cutruntools2` but the example configuration files that live in `config/` reference `cutruntools2.1`.

**Comment by fl-yu** [comment]
Thank you for your feedback! I have changed cutruntools2 to cutruntools2.1 in `install/environment1.yml` to be coherent with instruction for installation with conda separately. 
I will close this thread but please feel free to reopen it if you have questions.
