### ISSUE TITLE
required sample.bed

### ISSUE THREAD

**Issue by garci1294** [fl-yu/CUT-RUNTools-2.0#6]
Thank you for sharing this great tool @fl-yu!

In the `assemblies.install.sh` header it states that we need a sample.bed in the current directory. Can you please elaborate a little more? Is this sample.bed file provided by the pipeline or do we provide a blank file named sample.bed?

I will be using hg38.

Here is the line of code from `assemblies.install.sh` that needs this file.
`$bedtoolsbin/bedtools getfasta -fi ${organism_build}.fa -bed ../../sample.bed`

Thank you,
Jesus

**Comment by fl-yu** [comment]
Hey garci1294,

Thanks for your interest in our software!

Don't worry about this although there will be an error message. We just use `getfasta` function to generate an index for the genome.fa file (create *.fai index file), so you don't need to have a real bed file here.
I have added some annotations for this, please download a new `assemblies.install.sh` script from the repository.

**Comment by garci1294** [comment]
This makes sense. Thank you @fl-yu !
