### ISSUE TITLE
Mapping multiple lane for bulk 

### ISSUE THREAD

**Issue by nandankita** [fl-yu/CUT-RUNTools-2.0#60]
How can I map multiple lanes at once? My fastq files are named as: 

1. CCRR_S13_L001_R1_001.fastq.gz
2. CCRR_S13_L001_R2_001.fastq.gz
3. CCRR_S13_L002_R1_001.fastq.gz
4. CCRR_S13_L002_R2_001.fastq.gz

I tried giving sample name as CCRR_S13_L001 but it does not map all 4.

**Comment by fl-yu** [comment]
I think it will be easier to merge fastq files with the same end first, by using `cat` command, then you will have two fastq files of each end to be modified in the naming rule. 
For example,
cat CCRR_S13_L001_R1_001.fastq.gz CCRR_S13_L002_R1_001.fastq.gz > CCRR_S13_R1_001.fastq.gz
Please let me know if it doesn't work.
