### ISSUE TITLE
Install patched version of  Atactk failed

### ISSUE THREAD

**Issue by PeggySze** [fl-yu/CUT-RUNTools-2.0#9]
Hi, I tried to install patched version of  Atactk by following installation Instructions but failed. The follwing is the error information when running the atactk.install.sh script :
```
patch -p0 -N --dry-run --silent make_cut_matrix < make_cut_matrix.patch 2> /dev/null
```
```
2 out of 2 hunks FAILED
```
```
patch -p0 -N --dry-run --silent metrics.py < metrics.py.patch 2> /dev/null
```
```
3 out of 3 hunks FAILED
```
Could anyone please tell me how to fix this problem ? Thanks!

**Comment by fl-yu** [comment]
Hi I am not sure what is the issue here, if this is helpful? https://stackoverflow.com/questions/14282617/hunk-1-failed-at-1-whats-that-mean
If it does not work, you could choose to manually patch the script as only a few lines needed to be changed.

**Comment by PeggySze** [comment]
Thanks for your quick reply!  I rerun the script and it finally worked. I guess previous error is caused by unproper git clone.  Appreciate your kindly help !

**Comment by fl-yu** [comment]
Great to hear it works.

The random top 1000 peaks setting is inherited from the last version. 
Our consideration is an appreciated peak number is useful to capture the true biological insights (top 2000). To make it more robust to peak calling results, we used 1000 random peaks.  

BTW please open a new issue if you have further questions/issues. Thanks!
